services:

  fastapi:
    build: ./fastapi
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./fastapi:/app
    depends_on:
      mysql:
        condition: service_healthy

  react:
    build: ./react
    container_name: react
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h $$MYSQL_HOST -u $$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
