FROM python:3.12-slim

# 作業ディレクトリ
WORKDIR /app

# 依存パッケージのインストール
COPY ./fastapi/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# FastAPI アプリ本体のコピー
COPY ./fastapi/fastapi_app /app/fastapi_app

# Gunicorn + Uvicorn Worker で実行
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "fastapi_app.main:app", "--bind", "0.0.0.0:80", "--workers", "2"]
